// Array maestro de etiquetas — la IA elige las más relevantes
export const FoodTags = [
  // Estado y frescura
  'fresco',
  'maduro',
  'verde',
  'seco',
  'congelado',
  'enlatado',
  'procesado',
  'orgánico',
  'natural',
  // Tipo de alimento
  'fruta',
  'verdura',
  'legumbre',
  'cereal',
  'lácteo',
  'proteína',
  'carne',
  'pescado',
  'mariscos',
  'huevo',
  'semilla',
  'nuez',
  'aceite',
  'condimento',
  'especia',
  'bebida',
  'snack',
  'dulce',
  'pan',
  // Características nutricionales
  'alto en proteína',
  'alto en fibra',
  'alto en vitamina C',
  'rico en potasio',
  'bajo en calorías',
  'alto en calcio',
  'fuente de hierro',
  'rico en omega-3',
  'antioxidante',
  'bajo en grasa',
  // Dieta
  'vegano',
  'vegetariano',
  'sin gluten',
  'sin lactosa',
  'keto',
  'paleo',
  'sin azúcar',
  // Preparación
  'listo para comer',
  'requiere cocción',
  'requiere refrigeración',
  'no perecedero',
  // Color (útil para búsqueda)
  'rojo',
  'verde',
  'amarillo',
  'naranja',
  'morado',
  'blanco',
  'marrón',
  // Origen
  'tropical',
  'importado',
  'local',
  'de temporada',
  // Uso culinario
  'para desayuno',
  'para almuerzo',
  'para cena',
  'para snack',
  'para bebida',
  'para postre',
  'para ensalada',
  'para sopa',
  'para batido',
  'para horneado',
];
